### ISSUE TITLE
[BUG] Sometimes don't open correctly in chrome

### ISSUE THREAD

**Issue by jrafaelg** [morethanwords/tweb#152]
**Describe the bug**
Sometimes don't open correctly in chrome

I can't give more information because I don't know what happens.

I tried the ctrl+f5 shortcut many times but it didn't work either.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser:  chrome 104
 - Version: webk

**Comment by BeTure20** [comment]
After doing some research, I find out that: Chrome and Safari only expose CacheStorage to the windowed context over HTTPS (Ref: https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage), so it's failed since I've not setup https yet.

I consider this as a bug since I always test the functionality of the service before doing some advanced stuffs (reverse proxy, https...etc), so I think it's abnormally to have this error and hope this can be fixed.

**Comment by jrafaelg** [comment]
I solved it for now

#154 

The blackbox extension for chrome apparently conflicts witch telegram web k
