### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by elitGithub** [morethanwords/tweb#193]
**Describe the bug**
When developing on top of your app, I add a key to the lang packs (for out example I'll use "Chat.Popup.NewTitle". It seems that it does not get recognised though - the formatter won't change it to the string I want (in our example - "My New Title").

**To Reproduce**
Add a new key to lang packs and try to append it to any new element (I created a new popup).

**Expected behavior**

**Screenshots**
Added thew new key:
![image](https://user-images.githubusercontent.com/52536795/213919798-0a94aee0-825e-471d-9a94-0b074bae1982.png)
Add it to the popup consutrctor:
![image](https://user-images.githubusercontent.com/52536795/213919820-fcb9e501-0868-4772-b222-6e0b1b53a5f4.png)
No translation:
![image](https://user-images.githubusercontent.com/52536795/213919855-7e1a3211-569e-48de-8495-5c5ff985a73f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu and Windows 11
 - Browser Chrome and Brave

**Additional context**
This is not a bug in the application, rather, it is a bug in how to correctly use the formatter/unclear results.

**Comment by morethanwords** [comment]
Increment `App.langPackCode` in `app.ts` in order to refresh language strings. Additionaly, you'd want to add translation for the string, then you have to use custom language on [translation platform](https://translations.telegram.org), convert the strings using `format_lang.js` script, and upload formatted `langPack.strings` to the platform. However, custom languages are yet to be supported.
