### ISSUE TITLE
Which API sites or protocal it uses to connect with Telegram Servers?

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [morethanwords/tweb#2]
eg. web.telegram.org uses
https://github.com/TelegramWeb/web.telegram.org#apis-for-testing
these additonal sites to connect with Telegram Servers. Please provide info on how it connects with Telegram Servers.

**Comment by morethanwords** [comment]
Application now uses websockets to communicate with Telegram. Here is the pattern:
wss://**[dc]**.web.telegram.org/apiws, [dc] should be replaced with name of it, such as **pluto**, **venus**, **aurora**, **vesta** or **flora**.

However, since it is based on the Webogram, you're able to use legacy protocol (HTTPS), and endpoints will be the same as yours.
