### ISSUE TITLE
About the implementation of the MTProtocol

### ISSUE THREAD

**Issue by kuangke9527** [morethanwords/tweb#202]
I checked the source code and did not find the socket connection code. I would like to ask is it implemented in wasm? I need help. Thanks.

**Comment by morethanwords** [comment]
[Here](https://github.com/morethanwords/tweb/blob/master/src/lib/mtproto/transports/websocket.ts) is the websocket part.

**Comment by 0x7d4** [comment]
Can you please explain how the requests are not shown in the network tab of the browser? because normally WS requests should be shown, but somehow they are not for telegram web.

a more detailed question that I asked on SO:
https://stackoverflow.com/questions/77549251/how-does-telegram-web-hide-its-api-requests-from-the-browser-network-tab

**Comment by pangrr** [comment]
+1

**Comment by pangrr** [comment]
src/lib/mtproto/transports is not shown in chrome Sources tab. Why?

**Comment by morethanwords** [comment]
> src/lib/mtproto/transports is not shown in chrome Sources tab. Why?

Because that part is in shared worker. Find mtproto.worker.ts here: chrome://inspect/#workers.
